server:
  port: 9002
spring:
  # jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # free marker
  freemarker:
    allow-request-override: false
    content-type: text/html
    suffix: .html
    charset: UTF-8
    cache: false
  mvc:
    static-path-pattern: /static/**
  # data source
  datasource:
    druid:
      username: root
      url: jdbc:mysql://47.106.198.5:3306/sirs?characterEncoding=utf-8&useSSL=false