server:
  port: 9002
spring:
  # jackson
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # free marker
  freemarker:
    allow-request-override: false
    content-type: text/html
    suffix: .html
    charset: UTF-8
    cache: false
  mvc:
    static-path-pattern: /static/**
  # data source
  datasource:
    druid:
      username: root
      password: xinan
      url: jdbc:mysql://47.106.198.5:3306/sirs?characterEncoding=utf-8&useSSL=false
  # mail
  mail:
    host: smtp.163.com
    username: 13023195022@163.com
    password: authcode666
    default-encoding: UTF-8
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
  redis:
    host: 47.106.198.5
    port: 6379
    password: xinan_redis
    timeout: 3000ms
    # 关于jedis的配置 org.springframework.boot.autoconfigure.data.redis.RedisProperties
    # 默认值： maxIdle = 8  minIdle = 0  maxActive = 8  maxWait = Duration.ofMillis(-1)

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.alibaba.xinan.sirs.entity
  configuration:
    # 自动转换驼峰命名
    map-underscore-to-camel-case: true
    # 对于映射未知列的行为 有三个属性可选 none warning failing
    auto-mapping-unknown-column-behavior: warning

pagehelper:
  auto-dialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

# shiro
shiro:
  hashAlgorithmName: MD5
  hashIterations: 1024